languages:
#  supported:
#    - am
#    - ka
#    - en
#    - de
#    - fr
#    - it
#    - ru
#    - am
#    - ar
#    - zh
#    - nl
#    - eo
#    - he
#    - ja
#    - nn
#    - pt
#    - sa
#    - hi
#    - es
#    - sv
#    - el
  supported:
    - de
    - fr
    - en
    - ru

links:
  wiktionary:
    base_url: 'https://dumps.wikimedia.org/'
    dumps:    'https://dumps.wikimedia.org/backup-index.html'

paths:
  dumpsFolder: "dumps/"
