languages:
  supported:
    - am
    - ka
    - bg
    - el
    - ps
    - ru
links:
  wiktionary:
    base_url: 'https://dumps.wikimedia.org/'
    dumps:    'https://dumps.wikimedia.org/backup-index.html'

paths:
  downloadsFolder: "wiktionary_dumps/"