name: Download Wiktionary Dump Files

on:
  schedule:
    - cron: "00 22 * * *" # Every day at the same time
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Dumps
        run: python3.10 src/wiktionary_dumps/download_wiktionary_dumps.py

        # For the future: Parse them directly as to overcome the github push limits in the normal as well as in the large file system

      - name: Setup Git Config
        run: |
          git config user.name "Dumps Bot"
          git config user.email "<>"

        # - Add all files which are smaller than 2 GB. This is used as a cache
        # -- Use normal git for files smaller than 100 MB
        # -- Otherwise, use git lfs
        # - If the file is larger than that it needs to be redownloaded next time for parse and cannot be cached on GitHub for it's too large

      - name: Git Track Large Files
        run: find * -size +100M -size -2G | xargs git lfs track

      - name: Git Add
        run: find * -size -2G -type f -print | xargs git add

      - name: Commit and Push
        run: |
          git commit -m "chore: downloaded dumps" --quiet
          git push origin main --quiet