name: Download Wiktionary Dump Files

on:
  schedule:
    - cron: "00 22 * * *" # Every day at 10 PM
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Dumps
        run: python3.8 src/wiktionary_dumps/download_wiktionary_dumps.py

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Wiktionary Dumps Bot"
          git config user.email "<>"

      - name: Commit Changes
        run: |
          git lfs track "src/wiktionary_dumps/**"
          git commit -m "chore: downloaded dumps"
          git push origin main
